version: '2.1'

services:
  bcnode:
    container_name: bcnode
    build:
      context: .
      args:
        - BUILD_FROM_HERE=${BUILD_FROM_HERE}
    image: trick77/bcnode:latest
    environment:
      - BC_MONITOR=false
      - BC_DEBUG=false
      - BC_LOG=info
    command: start --ws --rovers --node --ui --miner-key 0x725efa968f9be2687d4fae75d7b2bc67fadc06e7
    volumes:
      - data:/home/bc/bcnode/_data
      - ./conf:/home/bc/bcnode/config:ro
    ports:
    - "3000:3000"
    restart: unless-stopped

volumes:
  data:
